package com.shegs.idme

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.net.Uri
import android.provider.MediaStore
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.asAndroidBitmap
import androidx.compose.ui.platform.LocalContext
import androidx.core.content.FileProvider
import com.google.zxing.BarcodeFormat
import com.journeyapps.barcodescanner.BarcodeEncoder
import java.io.File
import java.io.FileOutputStream
import java.io.IOException

fun generateQRCode(text: String, size: Int): Bitmap {
    val barcodeEncoder = BarcodeEncoder()
    val bitmap = barcodeEncoder.encodeBitmap(text, BarcodeFormat.QR_CODE, size, size)
    return bitmap
}

fun shareQRCode(context: Context, qrBitmap: ImageBitmap) {

    val androidBitmap = qrBitmap.asAndroidBitmap()

    val shareIntent = Intent(Intent.ACTION_SEND).apply {
        type = "image/png"

        val qrImagePath = MediaStore.Images.Media.insertImage(
            context.contentResolver,
            androidBitmap,
            "QR Code",
            "QR Code generated by IdMe"
        )

        val qrImageUri = Uri.parse(qrImagePath)
        putExtra(Intent.EXTRA_STREAM, qrImageUri)
    }

    context.startActivity(Intent.createChooser(shareIntent, "Share QR Code"))
}